### ISSUE TITLE
Excel Crashes 

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1537]
Sadly i can't really provide any more information. 
With Commit: 1a93fc5632fff3ba88a778cebdfee7d0cb0f622f  everything is fine. 
But starting at Commit: 04263122dd52637b10c5e96bcfe1d3e95fc9b4c6 excel starts crashing at various occasions with a workbook with much code and some tests. 

Occasions are: Just navigating around, Opening Code inspections, some other. 

When the Crash occures excel just says it's crashed and the cpu load goes to 0 
```
Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	EXCEL.EXE
  Anwendungsversion:	14.0.7168.5000
  Anwendungszeitstempel:	56eade71
  Fehlermodulname:	KERNELBASE.dll
  Fehlermodulversion:	6.1.7601.23392
  Fehlermodulzeitstempel:	56eb30d1
  Ausnahmecode:	e0434352
  Ausnahmeoffset:	0000c54f
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031

Zusatzinformationen zum Problem:
  LCID:	1031
  skulcid:	1031

```
Translated: 
```
Problemsignature:
  ProblemEventName:	APPCRASH
  ApplicationName:	EXCEL.EXE
  ApplicationVersion:	14.0.7168.5000
  ApplicationTimestamp:	56eade71
  ErrorModuleName:	KERNELBASE.dll
  ErrorModuleVersion:	6.1.7601.23392
  ErrorModuleTimestamp:	56eb30d1
  ExceptionCode:	e0434352
  ExceptionOffset:	0000c54f
  OSVersion:	6.1.7601.2.1.0.256.48
  Locale-ID:	1031

Additional information:
  LCID:	1031
  skulcid:	1031

```

At a wild guess this is related to #1531  because my large workbook contains quiet a lot of functions that could cause this inspection. Since now these things somehow get duplicated maybe something is overflowing there ? 

Now that i found out how to debug: This is where it crashes though in debugger it doesnt crash it just rasies the exception: 

```
    public class UntypedFunctionUsageQuickFix : CodeInspectionQuickFix
    {
        public UntypedFunctionUsageQuickFix(ParserRuleContext context, QualifiedSelection selection) 
            : base(context, selection,
                  string.Format(InspectionsUI.QuickFixUseTypedFunction_,
                      context.GetText(), context.GetText().Insert(context.GetText().IndexOf('('), "$")))
        {
        }

        public override void Fix()
        {
            var originalInstruction = Context.GetText();
            var newInstruction = originalInstruction.Insert(originalInstruction.IndexOf('('), "$");
            var selection = Selection.Selection;

            var module = Selection.QualifiedName.Component.CodeModule;
            var lines = module.Lines[selection.StartLine, selection.LineCount];

            var result = lines.Replace(originalInstruction, newInstruction);
            module.ReplaceLine(selection.StartLine, result);
            // FIXME trigger reparse
        }
    }
```

![image](https://cloud.githubusercontent.com/assets/10895412/15391598/441f5494-1dc2-11e6-9413-a3a1d73ac9f4.png)
(the error reads: "the specified argument is out of range")

if i read this right this is the vba code where this occures: 
```
with rngTarget
        If objPicture.Width > .Width Then
            objPicture.Left = .Left + lngBorderOffset
            objPicture.Width = .Width - lngBorderOffset
        End If
end with
```
this should adapt the size of a picture 
the .left is not a string function
