### ISSUE TITLE
Rubberduck.Inspections assembly needs a build#

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3411]
Every release of Rubberduck includes `Rubberduck.Inspections.dll` version 1.0.0.0; I don't mind the 1.0 (it's a new assembly after all), but we need to be able to tell releases from the version number, e.g. "version 2.1.0.1234 shipped with Rubberduck.Inspections.dll v1.0.0.9876" - or, make all assemblies use the same version number.

**Comment by Vogel612** [comment]
I think it would make diagnosis easiest if the versions just matched...

**Comment by retailcoder** [comment]
Agreed. I think we need to tweak the .yml

```
assembly_info:
  patch: true
  file: RetailCoder.VBE\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
```

Needs a bit of research to find out if the format supports doing that for multiple assemblies.
